name: Build and Test sbgEComAnalyzer

on: [push, workflow_dispatch]

jobs:
  BuildAndTest:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          modules: 'qtlocation qtpositioning'

      - name: Configure
        run: cmake --preset release-qt

      - name: Build
        run: cmake --build --preset release-qt

      - name: Test
        run: ctest --preset release
